# Generated by Django 2.0.7 on 2018-07-26 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='deleted',
            field=models.DateTimeField(editable=False, null=True),
        ),
    ]
