# Generated by Django 2.0.7 on 2018-07-26 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0002_payment_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='deleted',
        ),
    ]
